---
test:
  oracle_cloud_defaults: &oracle_cloud_defaults
    user_id: ocid1.user.oc1..aaaaaaaa
    tenant_id: ocid1.tenancy.oc1..aaaaaaaa
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIBOwIBAAJBAMfW33yRX0zpGhFx8kvQcpip1pHG0QJVpUp7ik4W9JLl0PWqSudF
      eXF0hFAc+Vx9R7ufpxMZ4lp+10WetdObAzsCAwEAAQJBAIw8R1y9DymDst1nHucB
      AkoLdR2bbXS78WBRTX77MOobynsP5gJehUI8hEOkbzYIJNBlSS/3aFAHBrd72diL
      ZPECIQDnr3y/pug4gNsoOeDWPGPxmLbd8cK9LS4KA0jeQ2PbfQIhANzPzNaHwZ5R
      aV/TnK00HpNJQBSo4S4Qbfc6JkZsD2cXAiEAiMI4s/R07S16sBMCGdPJ9wl7ICWe
      Gwb5PyXTNIe5AQ0CIC5mzJjYdmuamBY3Fdmf9jzlS74LryZK9ZDae2iZFLOJAiA6
      7KHzcqovm0lETCaEKSMWhKEcIfmz4qbAqxbx+DmAlQ==
      -----END RSA PRIVATE KEY-----
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMfW33yRX0zpGhFx8kvQcpip1pHG0QJV
      pUp7ik4W9JLl0PWqSudFeXF0hFAc+Vx9R7ufpxMZ4lp+10WetdObAzsCAwEAAQ==
      -----END PUBLIC KEY-----
  oracle_oke_defaults: &oracle_oke_defaults
    cluster_id: ocid1.cluster.oc1..aaaaaaaa
    hostname: 1.2.3.4
    port: 6443
  oracle_cloud:
    <<: *oracle_cloud_defaults
  oracle_oke:
    <<: *oracle_oke_defaults
